#ifndef _LH_BRANDING_H_
#define _LH_BRANDING_H_

#define OS_PRODUCTNAME_COMPANY			0x01
#define OS_PRODUCTNAME_FAMILY_GENERIC	0x02
#define OS_PRODUCTNAME_FAMILY_SPECIFIC	0x04
#define OS_PRODUCTNAME_TYPE				0x08
#define OS_PRODUCTNAME_VERSION			0x10
#define OS_PRODUCTNAME_SPVERSION		0x20
#define OS_PRODUCTNAME_COPYRIGHT		0x40

NTSTATUS NTAPI
RtlGetOSProductName(OUT PUNICODE_STRING Buffer,
                    IN ULONG Flags);

#endif // _LH_BRANDING_H_
